trigger:
  branches:
    include:
      - prod

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: ProductionVariables

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - checkout: self

          - task: JavaToolInstaller@0
            displayName: 'Install Java 17'
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          - script: |
              java -version
            displayName: 'Check Java 17 version'

          - task: Maven@4
            displayName: 'Maven Clean and Package'
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx1024m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              jdkArchitectureOption: 'x64'
              goals: 'clean package'

          - task: Maven@4
            displayName: 'Run Junit Test'
            inputs:
              mavenPomFile: 'pom.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              jdkArchitectureOption: 'x64'
              goals: 'clean verify'
              options: '-Dspring.data.mongodb.uri=$(MONGODB_URI)'

          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/target/surefire-reports/*.xml'
              failTaskOnFailedTests: true

          - task: CopyFiles@2
            displayName: 'Copy JAR files to staging'
            inputs:
              contents: '**/target/*.jar'
              targetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'

  - stage: DeployToProd
    dependsOn: Build
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/prod')
    jobs:
      - deployment: DeployApp
        environment: 'Prod'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: 'AzureAppServiceConnection'
                    appName: 'onlineSupermarketOrderingApp'
                    package: $(Build.ArtifactStagingDirectory)/*.jar
